name: build

on:
  push:
    branches: [ develop ]

jobs:
  release:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install

      - name: Windows build
        run: npm run build-win

      - name: Get tag
        uses: oprypin/find-latest-tag@v1
        id: tagName
        with:
          repository: OttawaSTEM/scratch-arduino-link
          releases-only: true

      - name: Zip exe file to zip for Windows
        uses: papeloto/action-zip@v1
        with:
          files: dist/Scratch-Arduino-Link-Win-${{ steps.tagName.outputs.tag }}.exe
          dest: dist/Scratch-Arduino-Link-Win-${{ steps.tagName.outputs.tag }}.zip

      - name: Cleanup Windows artifacts
        run: npx rimraf "dist/!(*.zip)"

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/Scratch-Arduino-Link-*.*, index.json"
          tag: ${{ steps.tagName.outputs.tag }}
          token: ${{ secrets.SERVER_USER }}
          allowUpdates: true
